site_name: Relic Seekers Documentation
extra:
  analytics:
    provider: google
    property: G-RF1W1204MN
repo_url: https://github.com/Tomko-Code/Relic-Seekers
repo_name: Relic Seekers
theme:
  name: material
  
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode